### ISSUE TITLE
这个有什么实际作用吗？

### ISSUE THREAD

**Issue by Z-fly** [Xposed-Modules-Repo/com.yifeplayte.maxmipadinput#1]

**Comment by YifePlayte** [comment]
![Screenshot_2022-12-31-17-50-30-411_com yifeplayte maxmipadinput-edit](https://user-images.githubusercontent.com/62252171/210132406-62005a8c-969a-4a8d-a98b-d887c72077eb.jpg)
如果您使用的是MIUI14，可能旧版模块会失效。请更新检查功能是否生效。
