### ISSUE TITLE
esc key not working for redmi pad

### ISSUE THREAD

**Issue by Ankit2502** [Xposed-Modules-Repo/com.yifeplayte.maxmipadinput#2]
I know this is for mi pad 5 but I was wondering if you can also fix this issue for redmipad, even on it the esc button doesn't work or function...

我知道这是针对 mi pad 5 的，但我想知道你是否也可以为 redmipad 解决这个问题，即使它的 esc 按钮不起作用或不起作用......

**Comment by YifePlayte** [comment]
Can you provide module logs in Lsposed?

**Comment by Ankit2502** [comment]
Can you tell me how to take log of that??

Btw here is logs from lspossed module

Module log 
[LSPosed_2023-02-11T23_47_17.197270modules.zip](https://github.com/Xposed-Modules-Repo/com.yifeplayte.maxmipadinput/files/10714453/LSPosed_2023-02-11T23_47_17.197270modules.zip)

Verbose logs 
[LSPosed_2023-02-11T23_47_24.843129verbose.zip](https://github.com/Xposed-Modules-Repo/com.yifeplayte.maxmipadinput/files/10714454/LSPosed_2023-02-11T23_47_24.843129verbose.zip)
