### ISSUE TITLE
在小米平板6Pro上开启部分功能时，设备刷新率调节出现问题（游戏场景除外）

### ISSUE THREAD

**Issue by Wnky6457** [Xposed-Modules-Repo/com.yifeplayte.maxmipadinput#3]
当前系统版本：MIUIPad14.0.3（Android13）
模块版本：1.3.2
与问题有关的功能：去除触控笔蓝牙限制
具体问题：启用该功能后，设备的可调刷新率只剩60与120两档，90变60，144变120，除非把应用添加到游戏加速，为其手动指定刷新率

**Comment by YifePlayte** [comment]
@Wnky6457 理论上，触控笔蓝牙限制与刷新率无关。并且我手上没有小米平板6系列机器，无法测试。

**Comment by Wnky6457** [comment]
是的，确实很奇怪，我最后是一个一个模块和功能排查，最后查到是这个模块的这个功能的，虽然也想不通到底有什么关联。请问需要我协助测试吗，需要的话我能做些什么。

**Comment by Wnky6457** [comment]
> @Wnky6457 理论上，触控笔蓝牙限制与刷新率无关。并且我手上没有小米平板6系列机器，无法测试。

刚刚再次确认了一下，如果开启该功能并选择驱动版本1，则没有异常，选择驱动版本2才会导致上述的问题

**Comment by YifePlayte** [comment]
> > @Wnky6457 理论上，触控笔蓝牙限制与刷新率无关。并且我手上没有小米平板6系列机器，无法测试。
> 
> 刚刚再次确认了一下，如果开启该功能并选择驱动版本1，则没有异常，选择驱动版本2才会导致上述的问题

已确认，此问题与本模块无关，在小米平板6系列平板上使用官方二代笔之后即锁帧，由于本模块的解锁蓝牙限制原理即伪装已连接官方笔，而锁帧行为大概率是内核级的，因此模块无力解决此问题。
