### ISSUE TITLE
Bluetooth restriction doesnt work with mi pad 6

### ISSUE THREAD

**Issue by rslimshady112** [Xposed-Modules-Repo/com.yifeplayte.maxmipadinput#4]
on lsposed log it says:
Inited hook: RemoveStylusBluetoothRestriction: null

is this the reason?

**Comment by rslimshady112** [comment]
just checked, finger gesture option doesnt work either; gives the same null error

**Comment by YifePlayte** [comment]
Well, those "null" logs are normal since it indicates that there's no error when initializing hooks. I've received a lot of feedbacks about this function not working on Mi Pad 6, but since I don't have the device, I can't test it and those logs gives me no help.

**Comment by YifePlayte** [comment]
> just checked, finger gesture option doesnt work either; gives the same null error

However, finger nums swap for gesture should works just fine. Maybe try newer version of Lsposed?

**Comment by rslimshady112** [comment]
mb finger num swap worked now.
Maybe I could help you with needed files or other stuff if you are planning to update it for mi pad 6

**Comment by YifePlayte** [comment]
@rslimshady112 I've got some files I needed, but it seems like there's no difference between 5 and 6 in stylus. And it seems like this function works well on the Mi Pad 6 Pro. So perhaps I can't provide help on this.

**Comment by s2kaka** [comment]
mine work ok . pad 6 CN rom

**Comment by s2kaka** [comment]
> @rslimshady112 I've got some files I needed, but it seems like there's no difference between 5 and 6 in stylus. And it seems like this function works well on the Mi Pad 6 Pro. So perhaps I can't provide help on this.

My mipad 6 with MIUI 14.047 TMZCNXM 
Ignore long press stylus button is not working.
Can you help me with it

**Comment by s2kaka** [comment]
[LSPosed_2023-10-26T21_46_00.873521.zip](https://github.com/Xposed-Modules-Repo/com.yifeplayte.maxmipadinput/files/13177520/LSPosed_2023-10-26T21_46_00.873521.zip)


here is log file

**Comment by YifePlayte** [comment]
> > @rslimshady112 I've got some files I needed, but it seems like there's no difference between 5 and 6 in stylus. And it seems like this function works well on the Mi Pad 6 Pro. So perhaps I can't provide help on this.
> 
> My mipad 6 with MIUI 14.047 TMZCNXM Ignore long press stylus button is not working. Can you help me with it

Fixed.

**Comment by rslimshady112** [comment]
It was the pen, mpp doesnt work, AES or WGP not sure
