### ISSUE TITLE
请问可以增加屏蔽蓝牙键盘win键的功能吗，平板远程链接PC真的很需要这个功能！

### ISSUE THREAD

**Issue by lwm38741** [Xposed-Modules-Repo/com.yifeplayte.maxmipadinput#5]
win键，alt+tap组合键，还有esc键都是远程PC需要屏蔽才能更好的使用，目前支持了esc还好用，如果能增加win键和alt+tap组合键将更完美！

**Comment by YifePlayte** [comment]
@lwm38741 请配合隔壁 https://github.com/CwithW/MiuiPadMeta 使用。
